### ISSUE TITLE
problem not load items

### ISSUE THREAD

**Issue by pintureti2000** [aborroy/alfresco-ubuntu-installer#7]
great job! thanks! 

Share works fine, but in admin tools-users says "Error loading items" (Error al cargar elementos).

I use it without certificate (http), I have try this without good results:

https://connect.hyland.com/t5/alfresco-blog/shared-secret-communication-mode-for-repository-and-solr/ba-p/118583

king regards,

**Comment by aborroy** [comment]
Likely you need to apply this patch:
https://github.com/Alfresco/alfresco-docker-installer/blob/master/generators/app/templates/images/share/web-extension/share-config-custom-dev.xml#L3

**Comment by pintureti2000** [comment]
The same result, error loading items. I think can be solr, but I´m not sure.
